### ISSUE TITLE
error in the fake_previsions step

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-scheduler#2]
When it comes to the fake_previsions step, it fails with the following error : 
```
Starting fake_previsions_using_previou
s_years_forcing ...
Traceback (most recent call last):
  File "/hyfaa/bin/fake_previsions_using_previous_years_forcing.py", line 328, in <module>
    fake_previsions_using_previous_years_forcing(args.input_yaml_file, args.ndays, output_dir=args.output_dir, nyearsmax=args.nyearsmax, nprocs=args.nprocs, verbose=args.verbose)
  File "/hyfaa/bin/fake_previsions_using_previous_years_forcing.py", line 114, in fake_previsions_using_previous_years_forcing
    extract_ensemble_member(hydrological_state_ens_start_path, hydrological_state_start_path, ii_ens_selection, compression_level=4)
  File "/hyfaa/lib/python3.7/site-packages/hyfaa/database/hydrostates/hydrostates_db.py", line 280, in extract_ensemble_member
    assert ensemble_member < n_ensemble
AssertionError
```

**Context:**
Launching the run using the docker image.
Only change in the default configs: augmented the proc number to 10
I'm running on commit #78b44a73 (March, 23)

**Comment by jeanpommier** [comment]
ping @remijugier

**Comment by vpimag** [comment]
Hello, 
There is actually an error in the code that I corrected but I am not allowed to push my solution.

**Comment by vpimag** [comment]
I've corrected this bug. Could you please give it a try before I consider the next ticket?

**Comment by jeanpommier** [comment]
It seems OK. I've not investigated the data themselves yet, but there is no error reported and the files are produced, 
thanks !

**Comment by AdrienOceanNext** [comment]
Did not run here, get the error from issue #3
